- name: Deploy binary to EC2 instance
  hosts: web_servers
  become: yes
  tasks:
    - name: Copy binary to EC2 instance
      copy:
        src: ../main
        dest: /home/ec2-user/main
        mode: '0755'

    - name: Verify binary permissions
      command: ls -l /home/ec2-user/main

    - name: Run the binary (optional)
      command: /home/ec2-user/main
      register: binary_output

    - name: Display binary output (optional)
      debug:
        var: binary_output.stderr_lines
